EGG_DIRECTORY = 'assets/chicken/'

MODEL_HOODED = 'vulto-pedro'
EGG_HOODED   = EGG_DIRECTORY + MODEL_HOODED

MODEL_DOOR = 'door'
EGG_DOOR   = EGG_DIRECTORY + MODEL_DOOR

MODEL_KNOB = 'knob'
EGG_KNOB   =EGG_DIRECTORY + MODEL_KNOB