from panda3d.core import Vec4

EGG_DIRECTORY = 'assets/chicken/'

MODEL_HOODED = 'vulto-pedro'
EGG_HOODED   = EGG_DIRECTORY + MODEL_HOODED

MODEL_DOOR = 'door'
EGG_DOOR   = EGG_DIRECTORY + MODEL_DOOR

MODEL_KNOB = 'knob'
EGG_KNOB   =EGG_DIRECTORY + MODEL_KNOB

SOUND_DIRECTORY = 'assets/sounds'

MODEL_SKYDOME = 'skydome'
EGG_SKYDOME   = EGG_DIRECTORY + MODEL_SKYDOME

AMBIENT_LIGHT = Vec4(0.03, 0.03, 0.03, 1)

FOG_COLOR = Vec4(0, 0, 0, 1)
FOG_EXP_DENSITY = 0.04